


<?php
// Start the session at the very beginning
session_start();

// Include necessary files
require_once('../session.php');
require('process.php');

// Rest of your code...
?>



<!DOCTYPE html>
<html>
<head>
  <title>PARCON HOSPITAL</title>




  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">

  <!-- Include jQuery (required for DataTables) -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  <!-- Include DataTables JavaScript -->
  <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>



  <link rel="shortcut icon" href="../img/spa.ico" type="image/x-icon">
  <!-- Import Google Icon Font -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  <style>
    /* Custom CSS for the search field */
    .search-bar {
  display: flex;
  align-items: center;
  width: 300px;
  height: 40px;
  background-color: #f5f5f5;
  border-radius: 20px;
  overflow: hidden;
  box-shadow: 0 0px 0px rgba(47, 46, 46, 0.1);
  border: 3px solid #bbdefb; /* Set the border color */
}


    .search-bar input {
      flex: 1;
      border: none;
      outline: none;
      padding: 10px;
      font-size: 16px;
      background-color: transparent;
      text-align: center;
    }

    .search-bar button {
      border: none;
      background-color: #bbdefb;
      color: #fff;
      padding: 10px;
      border-radius: 0 20px 20px 0;
      cursor: pointer;
      transition: background-color 0.3s ease;
    }

    .search-bar button:hover {
      background-color: #f44211;
    }

  

    .add-button {
  background-color: #bbdefb;
  color: #ffffff;
  border-radius: 50%;
  border: 3px solid #bbdefb; 
  width: 40px;
  height: 40px;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-left: 20px;
   /* Add some margin to separate the buttons */
}




/* Add overlay form */
.overlay {
  display: none;
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: rgba(0, 0, 0, 0.7);
  z-index: 1;
  text-align: center;
  overflow: auto; /* Add this property to enable scrolling */
}

.form-container {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  background: white;
  padding: 20px;
  border-radius: 5px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
  max-width: 90vw;
  max-height: 90vh;
  overflow: auto; /* Add this property to enable scrolling inside the form container */
}

@media (max-width: 768px) {
  .form-container {
    width: 90vw;
  }
}

@media (max-width: 480px) {
  .form-container {
    width: 95vw;
  }
}



.my-form {
  /* Form styles */
}

.close-button {
  margin-top: 10px;
  background-color: #ccc;
  border: none;
  padding: 5px 10px;
  cursor: pointer;
  border-radius: 5px;
}

.close-button:hover {
  background-color: #aaa;
}








/* Form registration styles */



.my-form h2 {
  text-align: center;
  margin-bottom: 20px;
}

.form-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 10px;
}

.form-row label {
  flex: 1;
  text-align: left;
  padding-right: 10px;
}

.form-row input {
  flex: 3;
}

.my-form button[type="submit"] {
  width: 100%;
  background-color: #4CAF50;
  color: white;
  padding: 10px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  transition: background-color 0.3s;
}

.my-form button[type="submit"]:hover {
  background-color: #45a049;
}






/* color blue of button in table  */

.blue-button {
        background-color: lightblue;
        color: white; /* Text color is set to white for visibility */
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }











    /* Target the search input generated by DataTables */
    div.dataTables_wrapper input[type="search"] {
        width: 100%;
        padding: 10px;
        border: 1px solid #e5e5e5;
        border-radius: 4px;
        background-color: #f5f5f5;
        color: #333;
        font-size: 14px;
        transition: border-color 0.2s, box-shadow 0.2s;
    }

    /* Style the search input when focused */
    div.dataTables_wrapper input[type="search"]:focus {
        border-color: #007bff;
        box-shadow: 0 0 5px rgba(0, 123, 255, 0.5);
    }




    body {
  background-image: url('../img/stock.jpg');
  background-size: cover;
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-position: center center;
}






  </style>

</head>
<body>




<!-- Navbar Start -->
<nav>
  <div class="nav-wrapper blue lighten-1">

    <a href="index.html" class="brand-logo">
        <div style="max-width: 60px; max-height: 60px;">
          <img src="../img/spa.png" alt="Logo Description" style="width: 100%; height: 100%; object-fit: contain;">
        </div>
      </a>
      

    <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
    <li class="active-menu"><a href="index_in.php"><i class="fas fa-box"></i> In Stock</a></li>
<li><a href="low_stock.php"><i class="fas fa-exclamation-triangle"></i> Low stock</a></li>
<li><form method="post" action="#" name="logoutForm">
    <a href="#" class="logout-link" onclick="document.logoutForm.submit();">
        <i class="fas fa-sign-out-alt"></i> Logout
    </a>
    <input type="hidden" name="end_session" value="1">
</form></li>
    </ul>
  </div>
</nav>

<ul class="sidenav" id="mobile-demo">
  <li><a href="about.html">In stock</a></li>
      <li><a href="about.html">Low stock</a></li>
      <li><a href="../login.php">Log out</a></li>
</ul>

<br>
<br>


<span>
  <button id="showFormButton" class="add-button" style="display: inline;">
    <i class="fas fa-plus"></i>
  </button>
  <button onclick="resetSearch()" class="add-button" style="display: inline;">
    <i class="fas fa-file-excel"></i>
  </button>
  <button id="toggleSearchButton" class="add-button" style="display: inline;">
  <i class="fas fa-search"></i>
  </button>



</span>


 
  
<br>
<br>

<table    id="yourTableID" class="display"  >
        <thead style="background-color: #bbdefb;">
            <tr>
                <th>Date</th>
                <th>Article</th>
                <th>Description</th>
                <th>Quantity</th>
                <th>Purchased Price</th>
                <th>Selling Price</th>
                <th>Cost</th>
                <th>Invoice No.</th>
                <th>Invoice Date</th>
                <th>Supplier</th>
                <th>ROP</th>
                <th>Stock by</th>
                 <th>History</th>
            </tr>
        </thead>
        <tbody>
            <?php include 'process.php'; // Include the PHP file here ?>

            <?php while ($row = $pharmacy_product->fetch_assoc()): ?>
                <tr>
                    <td><?= $row['day'] ?></td>
                    <td><?= $row['article'] ?></td>
                    <td><?= $row['info'] ?></td>
                    <td><?= $row['quantity'] ?></td>
                    <td><?= $row['p_price'] ?></td>
                    <td><?= $row['price'] ?></td>
                    <td><?= $row['cost'] ?></td>
                    <td><?= $row['invoice_no'] ?></td>
                    <td><?= $row['invoice_date'] ?></td>
                    <td><?= $row['supplier'] ?></td>
                    <td><?= $row['rop'] ?></td>
                    <td><?= $row['stocker'] ?></td>
                    <td>
                    <button class="blue-button" onclick="viewHistory(<?= $row['id'] ?>)">
    <i class="fa fa-history"></i> View History
</button>
        </td>
                </tr>
            <?php endwhile; ?>
        </tbody>
    </table>



<div id="overlay" class="overlay">
  <div id="formContainer" class="form-container">
    <form id="registrationForm" class="my-form" action="process.php" method="post">
    <img src="../img/phead.jpg" alt="New Header Image" style="max-width: 100%;">



      <div class="form-row">
        <label for="text">Article:</label>
        <input type="text"  name="article" required>
        
      </div>

      <div class="form-row">
        <label for="text">Unit:</label>
        <input type="text" name="info" required>
       
      </div>

      <div class="form-row">
        <label for="text">Quantity:</label>
        <input type="text"  name="quantity" required>
     
      </div>


      <div class="form-row">
        <label for="text">Purchased Price:</label>
        <input type="text"  name="p_price" required>
        
      </div>


      <div class="form-row">
        <label for="text">Selling Price:</label>
        <input type="text"  name="price" required>
        
      </div>
      <div class="form-row">
        <label for="text">Supplier:</label>
        <input type="text"  name="supplier" required>
        
      </div>

      <div class="form-row">
        <label for="text">Invoice No:</label>
        <input type="text"  name="invoice_no" required>
        
      </div>
      
      <div class="form-row">
        <label for="text">Invoice Date:</label>
        <input type="date"  name="invoice_date" required>
        
      </div>


      <div class="form-row">
        <label for="text">ROP:</label>
        <input type="text" name="rop" required>
        
      </div>

      <div class="form-row">
    <label for="stocker">Stocker:</label>
    <input type="hidden" value="<?php echo $session_id; ?>" name="stocker" id="stocker" required>
</div>


      <div class="form-row">
        <label for="text">Date of Stock:</label>
        <input type="date"  name = "day" required>
      </div>

      <button type="submit" name="submit">ADD STOCK</button>
      <button type="submit" id="closeFormButton" class="close-button">CANCEL</button>
    </form>
    
  </div>
</div>











<script>



// Function to display the form when the button is clicked
document.getElementById("showFormButton").addEventListener("click", function () {
  document.getElementById("overlay").style.display = "block";
});

// Function to close the form
document.getElementById("closeFormButton").addEventListener("click", function () {
  document.getElementById("overlay").style.display = "none";
});

// Optionally, you can add more functionality to handle form submission









$(document).ready(function() {
    var table = $('#yourTableID').DataTable({
        "paging": true, // Enable pagination
        "lengthMenu": [10, 25, 50, -1], // Define the number of entries per page
        "info": true // Show entry count information
    });

    // Hide the search input initially
    $('.dataTables_filter').hide();

    $('#toggleSearchButton').on('click', function() {
        toggleSearchInput();
    });

    $('#searchButton').on('click', function() {
        performSearch(table);
    });
});

function toggleSearchInput() {
    var searchInput = $('.dataTables_filter');

    if (searchInput.is(':visible')) {
        searchInput.hide();
    } else {
        searchInput.show();
        $('#searchInput').focus();
    }
}

function performSearch(table) {
    var input = $('#searchInput').val().toLowerCase();

    // Use DataTables' built-in search
    table.search(input).draw();
}
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>
