
<!DOCTYPE html>
<html>
<head>
  <title>Pharmacy Management</title>



  <!-- Include DataTables CSS -->
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">

  <!-- Include jQuery (required for DataTables) -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  <!-- Include DataTables JavaScript -->
  <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>



  <link rel="shortcut icon" href="../img/spa.ico" type="image/x-icon">
  
  <!-- Import Google Icon Font -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  <style>
    /* Custom CSS for the search field */
    .search-bar {
  display: flex;
  align-items: center;
  width: 300px;
  height: 40px;
  background-color: #f5f5f5;
  border-radius: 20px;
  overflow: hidden;
  box-shadow: 0 0px 0px rgba(47, 46, 46, 0.1);
  border: 3px solid #bbdefb; /* Set the border color */
}


    .search-bar input {
      flex: 1;
      border: none;
      outline: none;
      padding: 10px;
      font-size: 16px;
      background-color: transparent;
      text-align: center;
    }

    .search-bar button {
      border: none;
      background-color: #bbdefb;
      color: #fff;
      padding: 10px;
      border-radius: 0 20px 20px 0;
      cursor: pointer;
      transition: background-color 0.3s ease;
    }

    .search-bar button:hover {
      background-color: #f44211;
    }

  

    .add-button {
  background-color: #bbdefb;
  color: #ffffff;
  border-radius: 50%;
  border: 3px solid #bbdefb; 
  width: 40px;
  height: 40px;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-left: 20px;
   /* Add some margin to separate the buttons */
}




/* Add overlay form */

.overlay {
  display: none;
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: rgba(0, 0, 0, 0.7);
  z-index: 1;
  text-align: center;
}

.form-container {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  background: white;
  padding: 20px;
  border-radius: 5px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
}

.my-form {
  /* Form styles */
}

.close-button {
  margin-top: 10px;
  background-color: #ccc;
  border: none;
  padding: 5px 10px;
  cursor: pointer;
  border-radius: 5px;
}

.close-button:hover {
  background-color: #aaa;
}








/* Form registration styles */

.my-form {
  max-height: 600px; /* Adjust the height as needed */
  overflow-y: auto;
}

.my-form h2 {
  text-align: center;
  margin-bottom: 20px;
}

.form-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 10px;
}

.form-row label {
  flex: 1;
  text-align: left;
  padding-right: 10px;
}

.form-row input {
  flex: 3;
}

.my-form button[type="submit"] {
  width: 100%;
  background-color: #4CAF50;
  color: white;
  padding: 10px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  transition: background-color 0.3s;
}

.my-form button[type="submit"]:hover {
  background-color: #45a049;
}






/* color blue of button in table  */

.blue-button {
        background-color: lightgreen;
        color: black; /* Text color is set to white for visibility */
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }







    /* Target the search input generated by DataTables */
    div.dataTables_wrapper input[type="search"] {
        width: 100%;
        padding: 10px;
        border: 1px solid #e5e5e5;
        border-radius: 4px;
        background-color: #f5f5f5;
        color: #333;
        font-size: 20px;
        transition: border-color 0.2s, box-shadow 0.2s;
    }

    /* Style the search input when focused */
    div.dataTables_wrapper input[type="search"]:focus {
        border-color: #007bff;
        box-shadow: 0 0 5px rgba(0, 123, 255, 0.5);
    }









    .overlay1 {
  display: none; /* Add this line to hide the overlay by default */
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: rgba(0, 0, 0, 0.7);
  z-index: 1;
  text-align: center;
}

.form-container1 {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  background: white;
  padding: 20px; /* Adjust padding as needed */
  width: 30%; /* Increase the width as needed */
  border-radius: 10px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
}

@media (max-width: 768px) {
  border-radius: 10px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
}

@media (max-width: 576px) {

  border-radius: 10px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
}



    /* Red Button for Delete */

    .submit-button {
  background-color: green;
  color: white;
  border: none;
  padding: 20px 35px; /* Increase the padding for width and height */
  cursor: pointer;
  border-radius: 10px; /* Increase the border-radius for rounded corners */
}

.cancel-button {
  background-color: red;
  color: white;
  border: none;
  padding: 20px 35px; /* Increase the padding for width and height */
  cursor: pointer;
  border-radius: 10px; /* Increase the border-radius for rounded corners */
}



body {
  background-image: url('../img/bg2.jpg');
  background-size: cover;
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-position: center center;
}




  </style>

</head>
<body>

  <a href="process.php"></a>

<!-- Navbar Start -->
<nav>
  <div class="nav-wrapper blue lighten-1">

    <a href="index.html" class="brand-logo">
        <div style="max-width: 60px; max-height: 60px;">
          <img src="../img/spa.png" alt="Logo Description" style="width: 100%; height: 100%; object-fit: contain;">
        </div>
      </a>
      

    <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
    <li class="active-menu"><a href="index_in.php"><i class="fas fa-box"></i> In Stock</a></li>
<li><a href="low_stock.php"><i class="fas fa-exclamation-triangle"></i> Low stock</a></li>
<li><a href="../login.php"><i class="fas fa-sign-out-alt"></i> Log out</a></li>

    </ul>
  </div>
</nav>

<ul class="sidenav" id="mobile-demo">
  <li><a href="about.html">In stock</a></li>
      <li><a href="about.html">Low stock</a></li>
      <li><a href="../login.php">Log out</a></li>
</ul>

<br>
<br>










<span>
 
  <button onclick="resetSearch()" class="add-button" style="display: inline;">
    <i class="fas fa-file-excel"></i>
  </button>
  <button id="toggleSearchButton" class="add-button" style="display: inline;">
  <i class="fas fa-search"></i>
  </button>



</span>


 
  
<br>
<br>

<table  id="yourTableID" class="display" >
        <thead style="background-color: #bbdefb;">
            <tr>
                <th>Date</th>
                <th>Article</th>
                <th>Description</th>
                <th>Quantity</th>
                <th>Purchased Price</th>
                <th>Selling Price</th>
                <th>Cost</th>
                <th>Invoice No.</th>
                <th>Invoice Date</th>
                <th>Supplier</th>
                <th>ROP</th>
                <th>Stock by</th>
                 <th>Action</th>
            </tr>
        </thead>
        <tbody>
    <?php include 'process.php'; // Include the PHP file here ?>

    <?php while ($row = $pharmacy_product->fetch_assoc()): ?>
        <?php if ($row['rop'] >= $row['quantity']): ?>
            <tr>
                <td><?= $row['day'] ?></td>
                <td><?= $row['article'] ?></td>
                <td><?= $row['info'] ?></td>
                <td><?= $row['quantity'] ?></td>
                <td><?= $row['p_price'] ?></td>
                <td><?= $row['price'] ?></td>
                <td><?= $row['cost'] ?></td>
                <td><?= $row['invoice_no'] ?></td>
                <td><?= $row['invoice_date'] ?></td>
                <td><?= $row['supplier'] ?></td>
                <td><?= $row['rop'] ?></td>
                <td><?= $row['stocker'] ?></td>
                <td>
                    <button class="blue-button" onclick="openForm1(<?= $row['id'] ?>,'<?= $row['price'] ?>','<?= $row['article'] ?>')">
                        <i class="fa fa-plus"></i> Add
                    </button>
                </td>
            </tr>
        <?php endif; ?>
    <?php endwhile; ?>
</tbody>

    </table>



<div id="overlay" class="overlay">
  <div id="formContainer" class="form-container">
    <form id="registrationForm" class="my-form" action="process.php" method="post">
      <h2> Pharmacy Stocks </h2>

      <div class="form-row">
        <label for="text">Article:</label>
        <input type="text"  name="article" required>
        
      </div>

      <div class="form-row">
        <label for="text">Description:</label>
        <input type="text" name="info" required>
       
      </div>

      <div class="form-row">
        <label for="text">Quantity:</label>
        <input type="text"  name="quantity" required>
     
      </div>

      <div class="form-row">
        <label for="text">Price:</label>
        <input type="text"  name="price" required>
        
      </div>
      <div class="form-row">
        <label for="text">Supplier:</label>
        <input type="text"  name="supplier" required>
        
      </div>

      <div class="form-row">
        <label for="text">Invoice No:</label>
        <input type="text"  name="invoice_no" required>
        
      </div>
      
      <div class="form-row">
        <label for="text">Invoice Date:</label>
        <input type="date"  name="invoice_date" required>
        
      </div>


      <div class="form-row">
        <label for="text">ROP:</label>
        <input type="text" name="rop" required>
        
      </div>

      <div class="form-row">
        <label for="text">Stocker:</label>
        <input type="text" name="stocker" required>
      </div>

      <button type="submit" name="submit">Stock-In</button>
      <button type="submit" id="closeFormButton" class="close-button">Close</button>
    </form>
    
  </div>
</div>










<div class="overlay1" id="overlay1">
    <div class="form-container1" id="form-container1">
        <form id="updateForm" action="process.php" method="post">
            <div class="form-column">
               
                <input type="hidden" id="field1" name="id">
                
            </div>
       <div class="form-row">
          
           <input type="text" name="quantity"  class="centered-text" placeholder = " Enter Quantity">
          
       </div>

      <div class="form-row">
          
          <input type="hidden" id="field2" name="price"  class="centered-text">
          <input type="hidden" id="field3" name="article"  class="centered-text">
          <input type="date" id="field3" name="day"  class="centered-text">
         
      </div>
      
            
            <button type="submit" name="restock" class="submit-button">
    <i class="fas fa-plus">ADD STOCK</i> 
</button>
            <button class="cancel-button"type="button" onclick="closeForm()">
             <i class="fas fa-trash">     CANCEL     </i></button>
        </form>
    </div>
</div>










<script>












function openForm1(id,price,article) {
    // Populate the form fields with the data
    document.getElementById('field1').value = id;
    document.getElementById('field2').value = price;
     document.getElementById('field3').value = article;

    


    // Show the overlay
    document.getElementById('overlay1').style.display = 'block';
}



        function closeForm() {
            // Hide the overlay
            document.getElementById('overlay1').style.display = 'none';
        }









// Optionally, you can add more functionality to handle form submission














$(document).ready(function() {
    var table = $('#yourTableID').DataTable({
        "paging": true, // Enable pagination
        "lengthMenu": [10, 25, 50, -1], // Define the number of entries per page
        "info": true // Show entry count information
    });

    // Hide the search input initially
    $('.dataTables_filter').hide();

    $('#toggleSearchButton').on('click', function() {
        toggleSearchInput();
    });

    $('#searchButton').on('click', function() {
        performSearch(table);
    });
});

function toggleSearchInput() {
    var searchInput = $('.dataTables_filter');

    if (searchInput.is(':visible')) {
        searchInput.hide();
    } else {
        searchInput.show();
        $('#searchInput').focus();
    }
}

function performSearch(table) {
    var input = $('#searchInput').val().toLowerCase();

    // Use DataTables' built-in search
    table.search(input).draw();
}


</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>
